#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Types-Serialiser
Version  : 1.01
Release  : 16
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.01.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Types-Serialiser-license = %{version}-%{release}
Requires: perl-Types-Serialiser-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(common::sense)

%description
NAME
Types::Serialiser - simple data types for common serialisation formats
SYNOPSIS
DESCRIPTION
This module provides some extra datatypes that are used by common
serialisation formats such as JSON or CBOR. The idea is to have a
repository of simple/small constants and containers that can be shared
by different implementations so they become interoperable between each
other.

%package dev
Summary: dev components for the perl-Types-Serialiser package.
Group: Development
Provides: perl-Types-Serialiser-devel = %{version}-%{release}
Requires: perl-Types-Serialiser = %{version}-%{release}

%description dev
dev components for the perl-Types-Serialiser package.


%package license
Summary: license components for the perl-Types-Serialiser package.
Group: Default

%description license
license components for the perl-Types-Serialiser package.


%package perl
Summary: perl components for the perl-Types-Serialiser package.
Group: Default
Requires: perl-Types-Serialiser = %{version}-%{release}

%description perl
perl components for the perl-Types-Serialiser package.


%prep
%setup -q -n Types-Serialiser-1.01
cd %{_builddir}/Types-Serialiser-1.01

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Types-Serialiser
cp %{_builddir}/Types-Serialiser-1.01/COPYING %{buildroot}/usr/share/package-licenses/perl-Types-Serialiser/9a56f3b919dfc8fced3803e165a2e38de62646e5
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Types::Serialiser.3
/usr/share/man/man3/Types::Serialiser::Error.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Types-Serialiser/9a56f3b919dfc8fced3803e165a2e38de62646e5

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Types/Serialiser.pm
/usr/lib/perl5/vendor_perl/5.34.0/Types/Serialiser/Error.pm
